import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { extensions, manga, type Extension, type Manga, type Status } from './data'
import './styles.css'

const nav = [{ icon: '⌂', label: 'Overview' }, { icon: '▤', label: 'My library' }, { icon: '◷', label: 'Updates' }, { icon: '✦', label: 'Extensions' }]
const statusColors: Record<Status, string> = { Reading: 'purple', 'Plan to read': 'gold', Completed: 'green', Paused: 'muted' }

function Cover({ item, large = false }: { item: Manga; large?: boolean }) { return <div className={`cover ${large ? 'cover-large' : ''}`} style={{ background: `linear-gradient(145deg, ${item.color}, #171827)` }}><span className="cover-mark">M</span><strong>{item.title}</strong><small>{item.author}</small></div> }
function App() {
  const [active, setActive] = useState('Overview'); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'All' | Status>('All'); const [toast, setToast] = useState(''); const [exts, setExts] = useState<Extension[]>(extensions)
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(''), 2600); return () => clearTimeout(t) }, [toast])
  const filtered = useMemo(() => manga.filter(m => (filter === 'All' || m.status === filter) && (m.title + m.author + m.genres.join(' ')).toLowerCase().includes(query.toLowerCase())), [filter, query])
  const toggle = (name: string) => setExts(e => e.map(x => x.name === name ? { ...x, enabled: !x.enabled } : x))
  return <div className="app">
    <aside><div className="brand"><span className="brand-icon">M</span><span>MANGROVE</span></div><div className="side-label">Workspace</div><nav>{nav.map(n => <button className={active === n.label ? 'active' : ''} onClick={() => setActive(n.label)} key={n.label}><span>{n.icon}</span>{n.label}{n.label === 'Updates' && <b>3</b>}</button>)}</nav><div className="side-bottom"><div className="side-label">Your space</div><button onClick={() => setToast('Collections are coming soon')}><span>▦</span>Collections</button><button onClick={() => setToast('Import your backup from Settings')}><span>⇩</span>Import library</button><div className="profile"><div className="avatar">A</div><div><strong>atharava205</strong><small>Free plan</small></div><span>•••</span></div></div></aside>
    <main><header><div className="breadcrumbs">Library <span>/</span> {active}</div><div className="header-actions"><div className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search your library..." /><kbd>⌘ K</kbd></div><button className="icon-button" onClick={() => setToast('No new notifications')}>♢</button><button className="help" onClick={() => setToast('Tip: use extensions to add more sources')}>?</button></div></header>
    {active === 'Extensions' ? <Extensions exts={exts} toggle={toggle} /> : <><section className="hero"><div><p className="eyebrow">MONDAY, SEPTEMBER 28, 2026</p><h1>Good evening, <em>reader.</em></h1><p className="sub">Your story continues here. Pick up where you left off.</p></div><button className="primary" onClick={() => setToast('Opening your next chapter…')}>Continue reading <span>→</span></button></section>
      <section className="stats"><div><span>Reading now</span><strong>12</strong><small className="up">↑ 2 this week</small></div><div><span>Chapters read</span><strong>284</strong><small className="up">↑ 18 this week</small></div><div><span>Library total</span><strong>47</strong><small>Across 3 extensions</small></div><div><span>Reading streak</span><strong>9 <small>days</small></strong><small className="fire">● Personal best!</small></div></section>
      <section className="section-head"><div><h2>{active === 'Updates' ? 'Recent updates' : active === 'My library' ? 'Your library' : 'Continue reading'}</h2><p>{active === 'Updates' ? 'New chapters from your followed series.' : 'Jump back into your current series.'}</p></div><div className="filters">{(['All', 'Reading', 'Plan to read', 'Completed'] as const).map(f => <button className={filter === f ? 'selected' : ''} onClick={() => setFilter(f)} key={f}>{f}</button>)}</div></section>
      <div className="manga-grid">{filtered.slice(0, 4).map(item => <article className="manga-card" key={item.id}><Cover item={item} /><div className="card-body"><div className="card-title"><h3>{item.title}</h3><button onClick={() => setToast(`${item.title} saved to favorites`)}>♡</button></div><p className="author">{item.author}</p><div className="progress-row"><span className={`pill ${statusColors[item.status]}`}>{item.status}</span><span>{item.read}/{item.chapters} ch.</span></div><div className="progress"><i style={{ width: `${item.read / item.chapters * 100}%` }} /></div><div className="card-foot"><span>Updated {item.updated}</span><span>★ {item.rating}</span></div></div></article>)}</div>
      {filtered.length === 0 && <div className="empty">No manga found. Try a different search.</div>}
      <section className="discovery"><div><p className="eyebrow">DISCOVER SOMETHING NEW</p><h2>Find your next<br /><em>favorite story.</em></h2><p>Search across all your enabled extensions<br />from one beautiful place.</p><button className="secondary" onClick={() => setActive('Extensions')}>Browse extensions <span>→</span></button></div><div className="stacked-covers"><Cover item={manga[1]} /><Cover item={manga[4]} /><Cover item={manga[5]} /></div></section>
    </>}
    </main>{toast && <div className="toast">✓ &nbsp; {toast}</div>}
  </div>
}
function Extensions({ exts, toggle }: { exts: Extension[]; toggle: (name: string) => void }) { return <section className="extensions"><div className="extension-hero"><div><p className="eyebrow">SOURCE MARKETPLACE</p><h1>Make your library <em>limitless.</em></h1><p className="sub">Extensions connect Mangrove to the catalogs you love.</p></div><button className="primary">＋ Add extension</button></div><div className="section-head"><div><h2>Installed extensions</h2><p>{exts.filter(x => x.enabled).length} active sources</p></div><button className="text-button">Browse marketplace →</button></div><div className="extension-list">{exts.map(x => <div className="extension" key={x.name}><div className="extension-icon" style={{ background: x.color }}>{x.icon}</div><div className="extension-info"><h3>{x.name} <span>v{x.version}</span></h3><p>{x.description}</p></div><label className="switch"><input type="checkbox" checked={x.enabled} onChange={() => toggle(x.name)} /><i /></label></div>)}</div><div className="developer-card"><span className="dev-icon">⌘</span><div><h3>Build your own extension</h3><p>Bring any public manga source to Mangrove with our simple adapter API.</p></div><button className="secondary">Read the docs →</button></div></section> }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
